name: aplikasi2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^2.10.0  # Latest stable version of firebase_core
  firebase_auth: ^4.6.1  # Latest stable version of firebase_auth
  cloud_firestore: ^4.5.0  # Add this if you're using Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    - assets/images/logo.png
    - assets/images/start.png
    - assets/images/bg.png
    - assets/images/bg2.png
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Sewer
      fonts:
        - asset: assets/fonts/sewer.ttf
          weight: 700
